openapi: 3.0.0
info:
  title: Command Executor API
  version: 1.0.0
servers:
  - url: http://localhost:9001
paths:
  /exec:
    post:
      summary: Execute a command in the terminal
      operationId: renderPage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - command
              properties:
                command:
                  type: string
                  example: echo Hello, world!
      responses:
        200:
          description: Command executed
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: stdout
                  message:
                    type: string
                    example: Hello, world!\n
    get:
      summary: Retrieve a list of Figma files
      responses:
        200:
          description: Successfully retrieved Figma files
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    get:
      summary: Retrieve the pages of a specific Figma file
      parameters:
        - name: fileKey
          in: path
          required: true
          schema:
            type: string
        - name: pageId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved Figma page information
          content:
            application/json:
              schema:
                type: object
